Portfolio: Mobile version
B77748/arnaud_portfolio pull request #3
Opened 2022-03-22 20:22 UTC by B77748

Add a contact form with :
- background Image and background color
- Title of my contact 
- Paragraph of my contact 
- A form with input type text and email and textarea and button for submitting

2022-03-22 21:21 UTC, elmar8287 requested changes
Hi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

- No linter issues 👍 
- Nice design, considering the Figma template! 👍 

## Required Changes ♻️

- [ ] Check the comments under the review.

## Optional suggestions

- Please, consider creating an informative README file. You can use [MICROVERSE template](https://github.com/microverseinc/readme-template/blob/master/README.md) 👍 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 21:21 UTC, elmar8287 commented on index.html
> +                <form action="/contact-me" method="post">
- [ ] Please, consider that action value should be similar to `https://formspree.io/f/{form_id}`. Actually, your form is not submitting - just redirect to the not available `contact-me` page.

2022-03-22 21:21 UTC, elmar8287 commented on index.html
> +                    </ul>
- [ ] You can use simple form structure, without the `ul`/`li`. I know, you can fix it easily 👍

2022-03-22 21:21 UTC, elmar8287 commented on index.html
> +                            <textarea name="message" cols="35" rows="10">Type your message</textarea>
- [ ] Please, consider adding the `required` for the `textarea`
- [ ] Please, try to remove the text `Type your message` and give `placeholder` 👍 
- [ ] Please, consider that your `teaxtarea` has `maxlength="500"` attribute.

2022-03-22 21:21 UTC, elmar8287 commented on index.html
> +                            <input type="email" name="email" placeholder="Type your email">
- [ ] Please, consider adding the `required` for inputs 👍 
- [ ] Please, consider that the name input has `maxlength="30"` attribute 👍

2022-03-23 00:49 UTC, keroloussamy requested changes
Hi @B77748, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 00:49 UTC, keroloussamy commented on index.html
> +                <form action="https://formspree.io/f/form_id" method="post">
- [ ] Kindly your form still not working, First you have to create an account on [Formspree service](https://formspree.io/html) after that add a new form like in this pic
![image](https://user-images.githubusercontent.com/35535130/159598607-d4a0045f-e082-46ef-a6e3-b80bc8599aaf.png)

After that open, the integration tab and you will find your link with the id. Take it cope and replace it with this line `https://formspree.io/f/form_id`.

![image](https://user-images.githubusercontent.com/35535130/159598789-8bbac3c8-2a8a-4909-80aa-e5af88aa9cd2.png)

Try to test your form first before you request a review again the page after submitting should say `Thank you` work, not `Form not found.

Your page currently says after submitting 
![image](https://user-images.githubusercontent.com/35535130/159600097-08d91f5d-9d52-44fa-9998-0b53007f013d.png)

2022-03-23 01:05 UTC, keroloussamy approved these changes
Hi @B77748, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 01:13 UTC, merged